oasystem:
  name: 数据技术公司科研项目管理系统
  version: 1.0
  copyrightYear: 2023
  author: 范佳兴

server:
  port: 9999

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///oasystem

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  redis:
    port: 6379
    host: localhost

  logging:
    level:
      com.sjjs.oasysyem: debug

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



